### ISSUE TITLE
AVID Mitigations

### ISSUE THREAD

**Issue by ngatilio** [avidml/avid-db#13]
Hi,

Great job. Please, refer to this work for ML threat mitigations: https://arxiv.org/pdf/2207.00091.pdf. We are also implementing an AI SOAR feature to help prevent vulnerabilities in AI tools and mitigate against AI threats (see CertEye EOAR feature) : https://oecd.ai/fr/catalogue/tools/certeye and https://github.com/ngatilio/CertEye.

Please cite MITRE ATLAS if some TTPs where extracted from their database.

Thanks,
-------
Lionel Tidjon, Ph.D
Founder, Certkor.ai

**Comment by shubhobm** [comment]
Covered by https://github.com/avidml/avid-db/issues/3.
