### ISSUE TITLE
Lifecycle view

### ISSUE THREAD

**Issue by priamai** [avidml/avid-db#4]
Hi there,
The CRISP-DM is a good start but it's very data mining centric, we should enable a more modular approach to add other life cycles.
For example I would like to reference this beautiful [framework ](https://martinfowler.com/articles/cd4ml.html) by our beloved Martin Fowler or the most recent one proposed by Eugene Neelou at a SANS event.
We need more flexibility as this is will be quite a dynamic and exciting landscape.

**Comment by shubhobm** [comment]
Agreed. This is evolving into the work of the current taxonomy group and we're zeroing in on a MISP based standardization (thanks to you!)
