### ISSUE TITLE
ATLAS cross referencing

### ISSUE THREAD

**Issue by priamai** [avidml/avid-db#6]
Hi there,
would be beneficial to reference ATLAS incidents.
For example the [TAY incident ](https://avidml.org/database/avid-2022-v013/) should link to the [study](https://atlas.mitre.org/studies/AML.CS0009).
We should use the same approach of the CVE reference fields.
Cheers.

**Comment by shubhobm** [comment]
added case studies: https://github.com/avidml/avid-db/pull/7
added ATLAS and CVE connectors in `avidtools`
